package com.fnakhsan.toprotobufconverter.converter.template

//    https://protobuf.com/docs/language-spec#identifiers-and-keywords
object Keyword {
    const val SYNTAX = "syntax"
    const val EDITION = "edition"
    const val IMPORT = "import"
    const val WEAK = "weak"
    const val PUBLIC = "public"
    const val PACKAGE = "package"
    const val OPTION = "option"
    const val INF = "inf"
    const val NAN = "nan"
    const val MESSAGE = "message"
    const val ENUM = "enum"
    const val SERVICE = "service"
    const val EXTEND = "extend"
    const val GROUP = "group"
    const val ONEOF = "oneof"
    const val MAP = "map"
    const val EXTENSIONS = "extensions"
    const val RESERVED = "reserved"
    const val RPC = "rpc"
    const val STREAM = "stream"
    const val RETURNS = "returns"
    const val TO = "to"
    const val MAX = "max"
    const val REPEATED = "repeated"
    const val OPTIONAL = "optional"
    const val REQUIRED = "required"
    const val STRING = "string"
    const val BYTES = "bytes"
    const val INT32 = "int32"
    const val INT64 = "int64"
    const val UINT32 = "uint32"
    const val UINT64 = "uint64"
    const val SINT32 = "sint32"
    const val SINT64 = "sint64"
    const val FIXED32 = "fixed32"
    const val FIXED64 = "fixed64"
    const val SFIXED32 = "sfixed32"
    const val SFIXED64 = "sfixed64"
    const val BOOL = "bool"
    const val FLOAT = "float"
    const val DOUBLE = "double"
}